# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv flake8 pytest codecov
        pipenv sync --dev
    - name: Pytest
      run: |
        pipenv run pytest
    - name: flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names 
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics 
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide 
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Relatorio Coverage
      env:
        CODECOV_TOKEN: 'f66f4b91-6746-4275-bf5f-2efba479abee'
      run: |
        pipenv run codecov
    - name: Teste cov
      run: |
        pipenv run pytest --cov=libprotools